export const END_POINTS = {
  LOGIN: "/Userlogin",
  REGISTER: "/Register",
  LOGOUT: "/logout",
  GET_USER: "/get-user",
  TERMS_UPDATE: "/UpdateUser",

  // for settings
  MY_DETAILS: "/MyDetails",
  BUSINESS_PROFILE: "/BusinessProfile",
  ADD_CERTIFICATE_HOURS: "/AddCertificateHours",
  ADD_ADDITIONAL_INFO: "/AdditionalPhotos",
  ADD_SOCIAL_PROFILE: "/Social",
  SOCIAL_DELETE: "/SocialDelete",
  UPDATE_PASSWORD: "/UpdatePassword",
  ADD_CONVERSATION: "/AddConversation",
  ADD_PAYMENT_DETAILS: "/AddPaymentDetails",
  ADD_BUSINESS_LOCATION: "/AddBusinessLocation",
  SETTING_PUBLISH: "/SettingPublish",
  USER_DETAILS: "/UserDetails",
  CUSTOM_ORDERS: "/OrdersList",
  GET_ORDER_DETAILS: "/GetOrderDetails",
  ORDER_CONFIRMED: "/OrderConfirm",
  ORDER_BEFORE_IMAGES: "/OrderBeforeImages",
  ORDER_AFTER_IMAGES: "/OrdeAfterImages",
};
